#!/bin/sh
n=$1
shift

export PARALLEL=yes
export vcpus=2
export net_admin=192.168.$((50+$n*2))
export net_public=192.168.$((51+$n*2))
export adminnetmask=255.255.254.0
export cloudvg=libvirt

export virtualcloud=c$n
export cloud=$virtualcloud
